#修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/doedclab/Padavan.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: MI-R3P
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
        sed -i '/ONFIG_FIRMWARE_INCLUDE_V2RAY/d' .config #删除配置项V2RAY支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TROJAN/d' .config #删除配置项TROJAN支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_KOOLPROXY/d' .config #删除配置项KP广告过滤
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSOBFS/d' .config #删除配置项SSOBFS混淆
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项内网穿透FRPC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项内网穿透FRPS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config #删除配置项内网穿透ZEROTIER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config #删除配置项smartdns
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN/d' .config #删除配置项smartdns
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME/d' .config #删除配置项ADGUARDHOME
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config #删除配置项SRELAY代理
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FTPD/d' .config #删除配置项FTPB服务器
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD/d' .config #删除配置项SMB服务器
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD36/d' .config #删除配置项SMB服务器
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD_SYSLOG/d' .config #删除配置项SMB服务器
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WINS/d' .config #删除配置项SMB服务器
        sed -i '/CONFIG_FIRMWARE_ENABLE_USB/d' .config #删除配置项USB支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HID/d' .config #删除配置项USB支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SERIAL/d' .config #删除配置项USB支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_AUDIO/d' .config #删除配置项USB支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_UFSD/d' .config #删除配置项文件系统支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_FAT/d' .config #删除配置项文件系统支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXFAT/d' .config #删除配置项文件系统支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT2/d' .config #删除配置项文件系统支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT3/d' .config #删除配置项文件系统支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT4/d' .config #删除配置项文件系统支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_XFS/d' .config #删除配置项文件系统支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_FUSE/d' .config #删除配置项文件系统支持
        sed -i '/CONFIG_FIRMWARE_ENABLE_SWAP/d' .config #删除配置项文件系统支持
        sed -i '/CONFIG_FIRMWARE_INCLUDE_UVC/d' .config #删除配置项UVC camera
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LPRD/d' .config #删除配置项LPRD打印机
        sed -i '/CONFIG_FIRMWARE_INCLUDE_U2EC/d' .config #删除配置项USB打印机
        sed -i '/CONFIG_FIRMWARE_INCLUDE_EAP_PEAP/d' .config #删除配置项EAP_PEAP
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XUPNPD/d' .config #删除配置项媒体服务相关
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIDLNA/d' .config #删除配置项媒体服务相关
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW/d' .config #删除配置项媒体服务相关
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' .config #删除配置项transmission
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d' .config #删除配置项transmission
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' .config #删除配置项aria
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' .config #删除配置项aria
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config #删除配置项DOGCOM
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config #删除配置项MINIEAP
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config #删除配置项NJIT_CLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WYY/d' .config #删除配置项网易云解锁
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WYYBIN/d' .config #删除配置项网易云解锁GO版本
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CADDY/d' .config #删除配置项在线文件管理服务
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CADDYBIN/d' .config #删除配置项集成caddu执行文件
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config 
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config        
        #override
        sed -i '/CONFIG_FIRMWARE_CPU_900MHZ/d' .config
        echo "CONFIG_FIRMWARE_CPU_900MHZ=y" >> .config
        #tunsafe
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=y" >> .config
        #openvpn
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_OPENVPN=y" >> .config
        #aliddns
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=y" >> .config
        #kms
        sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' .config
        echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=y" >> .config
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
